version: '3'
services:
  asi-postgres:
    image: postgres:latest
    ports:
      - '6000:5432'
    environment:
      POSTGRES_DB: asi-db
      POSTGRES_USER: asiuser
      POSTGRES_PASSWORD: asi12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}