version: '3'
services:
  asi-postgres:
    image: postgres:latest
    ports:
      - '6000:5432'
    environment:
      POSTGRES_DB: asi-db
      POSTGRES_USER: asiuser
      POSTGRES_PASSWORD: asi12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
  streamlit-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '8501:8501'
    volumes:
      - ./frontend/src:/src
volumes:
  postgres-data: {}