version: '3'
services:
  asi-postgres:
    image: postgres:latest
    ports:
      - '6000:5432'
    environment:
      POSTGRES_DB: asi-db
      POSTGRES_USER: asiuser
      POSTGRES_PASSWORD: asi12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
  streamlit-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '8501:8501'
    volumes:
      - ./frontend/src:/app
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_HEADLESS=true
  fastapi-be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - asi-postgres
    environment:
      DATABASE_URL: postgres://asiuser:asi12345@asi-postgres:5432/asi-db
    volumes:
      - ./backend:/app
volumes:
  postgres-data: {}